spring:
  datasource:
    url: jdbc:postgresql://risco-pos-venda-bb-prd.cvk5asnnedpe.sa-east-1.rds.amazonaws.com:5432/risco_pos_venda_bb_prd
    username: digitalrdsbp

external:
  generalBaseUrl: https://ecs.api.brasilprev.com.br
